try {} catch (c) {
    let t = 1;
}
